// Code generated by MockGen. DO NOT EDIT.
// Source: crypto/interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	crypto "github.com/leledumbo/fiskaly-coding-challenge/signing-service-challenge-go/crypto"
)

// MockKeyPair is a mock of KeyPair interface.
type MockKeyPair struct {
	ctrl     *gomock.Controller
	recorder *MockKeyPairMockRecorder
}

// MockKeyPairMockRecorder is the mock recorder for MockKeyPair.
type MockKeyPairMockRecorder struct {
	mock *MockKeyPair
}

// NewMockKeyPair creates a new mock instance.
func NewMockKeyPair(ctrl *gomock.Controller) *MockKeyPair {
	mock := &MockKeyPair{ctrl: ctrl}
	mock.recorder = &MockKeyPairMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyPair) EXPECT() *MockKeyPairMockRecorder {
	return m.recorder
}

// Deserialize mocks base method.
func (m *MockKeyPair) Deserialize(arg0 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deserialize", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deserialize indicates an expected call of Deserialize.
func (mr *MockKeyPairMockRecorder) Deserialize(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deserialize", reflect.TypeOf((*MockKeyPair)(nil).Deserialize), arg0)
}

// PrivateKey mocks base method.
func (m *MockKeyPair) PrivateKey() crypto.Key {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrivateKey")
	ret0, _ := ret[0].(crypto.Key)
	return ret0
}

// PrivateKey indicates an expected call of PrivateKey.
func (mr *MockKeyPairMockRecorder) PrivateKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrivateKey", reflect.TypeOf((*MockKeyPair)(nil).PrivateKey))
}

// PublicKey mocks base method.
func (m *MockKeyPair) PublicKey() crypto.Key {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublicKey")
	ret0, _ := ret[0].(crypto.Key)
	return ret0
}

// PublicKey indicates an expected call of PublicKey.
func (mr *MockKeyPairMockRecorder) PublicKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublicKey", reflect.TypeOf((*MockKeyPair)(nil).PublicKey))
}

// Serialize mocks base method.
func (m *MockKeyPair) Serialize() ([]byte, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Serialize")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Serialize indicates an expected call of Serialize.
func (mr *MockKeyPairMockRecorder) Serialize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Serialize", reflect.TypeOf((*MockKeyPair)(nil).Serialize))
}

// MockAlgorithm is a mock of Algorithm interface.
type MockAlgorithm struct {
	ctrl     *gomock.Controller
	recorder *MockAlgorithmMockRecorder
}

// MockAlgorithmMockRecorder is the mock recorder for MockAlgorithm.
type MockAlgorithmMockRecorder struct {
	mock *MockAlgorithm
}

// NewMockAlgorithm creates a new mock instance.
func NewMockAlgorithm(ctrl *gomock.Controller) *MockAlgorithm {
	mock := &MockAlgorithm{ctrl: ctrl}
	mock.recorder = &MockAlgorithmMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlgorithm) EXPECT() *MockAlgorithmMockRecorder {
	return m.recorder
}

// ConstructKeyPair mocks base method.
func (m *MockAlgorithm) ConstructKeyPair(priv []byte) (crypto.KeyPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConstructKeyPair", priv)
	ret0, _ := ret[0].(crypto.KeyPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConstructKeyPair indicates an expected call of ConstructKeyPair.
func (mr *MockAlgorithmMockRecorder) ConstructKeyPair(priv interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConstructKeyPair", reflect.TypeOf((*MockAlgorithm)(nil).ConstructKeyPair), priv)
}

// GenerateKeyPair mocks base method.
func (m *MockAlgorithm) GenerateKeyPair() (crypto.KeyPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateKeyPair")
	ret0, _ := ret[0].(crypto.KeyPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateKeyPair indicates an expected call of GenerateKeyPair.
func (mr *MockAlgorithmMockRecorder) GenerateKeyPair() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateKeyPair", reflect.TypeOf((*MockAlgorithm)(nil).GenerateKeyPair))
}

// Sign mocks base method.
func (m *MockAlgorithm) Sign(priv crypto.Key, data []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sign", priv, data)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sign indicates an expected call of Sign.
func (mr *MockAlgorithmMockRecorder) Sign(priv, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sign", reflect.TypeOf((*MockAlgorithm)(nil).Sign), priv, data)
}

// Verify mocks base method.
func (m *MockAlgorithm) Verify(pub crypto.Key, data, signature []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", pub, data, signature)
	ret0, _ := ret[0].(error)
	return ret0
}

// Verify indicates an expected call of Verify.
func (mr *MockAlgorithmMockRecorder) Verify(pub, data, signature interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockAlgorithm)(nil).Verify), pub, data, signature)
}
